name: Merge Main to Develop

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge Main to Develop
        run: |
          git config user.name "tesla1729"
          git config user.email "your-email@example.com"
          git checkout develop
          git merge main --no-ff --no-edit
          git push origin develop
