name: Main to Develop

on:
  push:
    branches:
      - main

jobs:
  raise-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create pull request
        run: gh pr create -B develop -H main --title 'Merge main into develop' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
