name: Tag main branch with release branch name

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  tag-main-branch:
    runs-on: ubuntu-latest
    steps:   
      - name: Tag main branch with release branch name
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 1.1.2
          target: main
